document.addEventListener('DOMContentLoaded', () => {
	let data = [
		{
			name: 'Undergraduate Admissions',
			link: '//carleton.ca/admissions',
			category: 'Admissions',
			value: 'Undergraduate Admissions',
			tokens: [
				'Undergraduate Admissions',
				'Admissions',
				'Prospective students',
				'Future students',
				'programs',
			],
		},
		{
			name: 'Academic Advising Centre',
			link: '//carleton.ca/academicadvising/',
			category: 'Students',
			value: 'Academic Advising Centre ',
			tokens: ['Advising', 'Academic Advising Centre '],
		},
		{
			name: 'Co-operative Education',
			link: '//carleton.ca/co-op/',
			category: 'Students',
			value: 'Co-operative Education',
			tokens: ['co-op', 'Co-operative Education'],
		},
		{
			name: 'Collaborate: Carleton Campaign',
			link: '//futurefunder.carleton.ca/project/collaborate/',
			category: 'CU',
			value: 'CU',
			tokens: [
				'Collaborate',
				'Campaign',
				'fundraising',
				'contribute',
				'giv',
				'Collaborate: Carleton Campaign',
			],
		},
		{
			name: 'Care Report',
			link: '//carleton.ca/studentaffairs/care-report/',
			category: 'Students',
			value: 'Students',
			tokens: ['Care', 'Reports'],
		},
		{
			name: 'Proctoring services',
			link: '//carleton.ca/proctoring-services/',
			category: 'Students',
			value: 'Students',
			tokens: [
				'external exam',
				'proctoring',
				'proctor',
				'invigilation',
				'invigilator',
			],
		},
		{
			name: 'FutureFunder.ca',
			link: '//futurefunder.carleton.ca',
			category: 'CU',
			value: 'CU',
			tokens: ['Giving', 'Campaigns', 'Donate', 'support', 'giv', 'FutureFunder'],
		},
		{
			name: 'Graduate Admissions and Programs',
			link: '//graduate.carleton.ca/',
			category: 'Graduate',
			value: 'Graduate Admissions and Programs',
			tokens: [
				'Graduate Admissions and Programs',
				'Prospective Graduate',
				'Apply Graduate',
				'Grad',
				'Graduate',
				'Graduate Studies',
				'Master',
				'Master’s',
				'PhD',
				'Doctor',
				'Doctor of Philosophy',
				'Diplomas',
				'Post-grad',
				'Postgrad',
			],
		},
		{
			name: 'Faculty of Science',
			link: '//carleton.ca/science/',
			category: 'Faculty',
			value: 'Faculty of Science',
			tokens: ['Faculty of Science', 'Sci', 'Science'],
		},
		{
			name: 'Indigenous Initiatives, Centre for',
			link: '//carleton.ca/indigenous/',
			category: 'Students',
			value: 'Indigenous Initiatives, Centre for',
			tokens: ['Indigenous Initiatives, Centre for', 'Aboriginal'],
		},
		{
			name: 'Academic Success Centre, Student',
			link: '//carleton.ca/sasc/',
			category: 'Students',
			value: 'Academic Success Centre, Student',
			tokens: ['Academic Success Centre, Student'],
		},
		{
			name: 'Accountability',
			link: '//carleton.ca/about/university-executive/public-accountability/',
			category: 'About',
			value: 'Accountability',
			tokens: ['Accountability'],
		},
		{
			name: 'Admissions',
			link: '//carleton.ca/prospective/',
			category: 'Admissions',
			value: 'Admissions',
			tokens: ['Admissions, Prospective'],
		},
		{
			name: 'Aerospace Engineering, Department of Mechanical and',
			link: '//www.mae.carleton.ca/',
			category: 'Department',
			value: 'Aerospace Engineering, Department of Mechanical and',
			tokens: ['Aerospace Engineering, Department of Mechanical and'],
		},
		{
			name: 'African Studies',
			link: '//carleton.ca/africanstudies/',
			category: 'Department',
			value: 'African Studies',
			tokens: ['African Studies'],
		},
		{
			name: 'Alumni Services',
			link: '//alumni.carleton.ca',
			category: 'Alumni',
			value: 'Alumni Services',
			tokens: ['Alumni Services', 'Advancement'],
		},
		{
			name: 'Anthropology, Department of Sociology and',
			link: '//carleton.ca/socanth',
			category: 'Department',
			value: 'Anthropology, Department of Sociology and',
			tokens: ['Anthropology, Department of Sociology and'],
		},
		{
			name: 'Applied Language Studies, School of Linguistics and',
			link: '//carleton.ca/slals/',
			category: 'Department',
			value: 'Applied Language Studies, School of Linguistics and',
			tokens: [
				'Applied Language Studies, School of Linguistics and',
				'Russian',
				'Japanese',
				'Spanish',
			],
		},
		{
			name: 'Archives',
			link: '//carleton.ca/archives/',
			category: 'Information',
			value: 'Archives',
			tokens: ['Archives', 'Records'],
		},
		{
			name: 'Art and Culture, School for Studies in',
			link: '//carleton.ca/ssac',
			category: 'Department',
			value: 'Art and Culture, School for Studies in',
			tokens: ['Art and Culture, School for Studies in'],
		},
		{
			name: 'Art Gallery, Carleton University',
			link: '//cuag.ca',
			category: 'FASS',
			value: 'Art Gallery, Carleton University',
			tokens: ['CUAG', 'Art Gallery, Carleton University'],
		},
		{
			name: 'Art History (School for Studies in Art and Culture',
			link: '//carleton.ca/arthistory/',
			category: 'Department',
			value: 'Art History (School for Studies in Art and Culture',
			tokens: ['Art History (School for Studies in Art and Culture'],
		},
		{
			name: 'Arthur Kroeger College of Public Affairs',
			link: '//carleton.ca/akcollege/',
			category: 'Department',
			value: 'Arthur Kroeger College of Public Affairs',
			tokens: ['Arthur Kroeger College of Public Affairs'],
		},
		{
			name: 'Arts and Social Sciences, Faculty of',
			link: '//carleton.ca/fass/',
			category: 'Department',
			value: 'Arts and Social Sciences, Faculty of',
			tokens: ['Arts and Social Sciences, Faculty of'],
		},
		{
			name: 'Associate Vice-President (Student Support Services)',
			link: '//carleton.ca/studentsupport/',
			category: 'Students',
			value: 'Associate Vice-President (Student Support Services)',
			tokens: ['Associate Vice-President (Student Support Services)'],
		},
		{
			name: 'Athletics',
			link: '//athletics.carleton.ca',
			category: 'Service',
			value: 'Athletics',
			tokens: ['Athletics', 'Sports', 'fitness', 'pool', 'leagues'],
		},
		{
			name: 'Awards, Scholarships and Financial Assistance',
			link: '//carleton.ca/awards/',
			category: 'Admissions',
			value: 'Awards, Scholarships and Financial Assistance',
			tokens: ['Awards, Scholarships and Financial Assistance'],
		},
		{
			name: 'Awards ( Graduate Studies )',
			link: '//carleton.ca/graduate-studies/awards-and-funding/',
			category: 'Graduate',
			value: 'Awards (Graduate Studies)',
			tokens: ['Awards ( Graduate Studies )', 'OSAP'],
		},
		{
			name: 'A-Z website index',
			link: '//carleton.ca/directories',
			category: 'Service',
			value: 'A-Z website index',
			tokens: ['A-Z website index', 'AZ', 'websites'],
		},
		{
			name: 'Azrieli School of Architecture and Urbanism',
			link: '//carleton.ca/architecture/',
			category: 'Department',
			value: 'Azrieli School of Architecture and Urbanism',
			tokens: ['Azrieli School of Architecture and Urbanism', 'Architecture'],
		},
		{
			name: 'Biochemistry, Institute of',
			link: '//carleton.ca/biochem/',
			category: 'Department',
			value: 'Biochemistry, Institute of',
			tokens: ['Biochemistry, Institute of'],
		},
		{
			name: 'Biology, Department of',
			link: '//carleton.ca/biology/',
			category: 'Department',
			value: 'Biology, Department of',
			tokens: ['Biology, Department of'],
		},
		{
			name: 'BIT ( Bachelor of Information Technology ) degree program',
			link: '//bitdegree.ca/',
			category: 'Department',
			value: 'BIT ( Bachelor of Information Technology ) degree program',
			tokens: ['BIT ( Bachelor of Information Technology ) degree program'],
		},
		{
			name: 'Board of Governors',
			link: '//carleton.ca/secretariat/boardofgovernors/',
			category: 'Administration',
			value: 'Board of Governors',
			tokens: ['Board of Governors'],
		},
		{
			name: 'Bookstore',
			link: '//carleton.ca/bookstore/',
			category: 'Service',
			value: 'Bookstore (University Centre)',
			tokens: [
				'Bookstore',
				'Bookstore',
				'Book Store',
				'Campus store',
				'Textbooks',
				'Store',
				'Books',
				'Apparel',
				'Shop',
				'Supplies',
				'Clothing',
				'Course materials',
				'T-Shirts',
				'Gifts',
				'Fan Gear',
			],
		},
		{
			name: 'Bursaries',
			link: '//carleton.ca/awards/bursaries/',
			category: 'Admissions',
			value: 'Bursaries',
			tokens: ['Bursaries'],
		},
		{
			name: 'Business, The Sprott School of',
			link: '//sprott.carleton.ca/',
			category: 'Faculty',
			value: 'Business, The Sprott School of',
			tokens: [
				'Business, The Sprott School of',
				'Business School',
				'Sprott',
				'Bachelor of Commerce',
				'Commerce',
				'Bcom',
				'Accounting',
				'Entrepreneurship',
				'Finance',
				'Information Systems',
				'International Business',
				'Management',
				'Marketing',
				'Supply Chain Management',
				'Bachelor of International Business - Bib ',
				'Global financial management and systems',
				'International Marketing and Trade',
				'International Strategy and Human Resources Management',
				'MBA',
				'Business Analytics',
				'Financial Management',
				'International Business (MBA)',
				'International Development Management',
				'PhD in Management',
			],
		},
		{
			name: 'Calendar, Graduate',
			link: '//carleton.ca/cugc/',
			category: 'Students',
			value: 'Calendar, Graduate',
			tokens: ['Calendar, Graduate', 'Courses'],
		},
		{
			name: 'Calendar, Undergraduate',
			link: '//carleton.ca/cuuc/',
			category: 'Students',
			value: 'Calendar, Undergraduate',
			tokens: ['Calendar, Undergraduate', 'Undergraduate', 'Undergrad', 'Courses'],
		},
		{
			name: 'Campus Card',
			link: '//carleton.ca/campuscard',
			category: 'Service',
			value: 'Campus Card',
			tokens: ['Campus Card', 'Card', 'Vending', 'doors'],
		},
		{
			name: 'Campus Tour',
			link: '//admissions.carleton.ca/campustours/',
			category: 'Admissions',
			value: 'Campus Tour',
			tokens: ['Campus Tour', 'Guided tours', 'Visit campus'],
		},
		{
			name: 'Canadian Union of Public Employees ( CUPE ) Local 2424',
			link: '//2424.cupe.ca/',
			category: 'Service',
			value: 'Canadian Union of Public Employees ( CUPE ) Local 2424',
			tokens: [
				'Canadian Union of Public Employees ( CUPE ) Local 2424',
				'CUPE 2424',
				'Union',
			],
		},
		{
			name: 'Campus Community Campaign',
			link: '//carleton.ca/campuscommunitycampaign/',
			category: 'Service',
			value: 'Campus Community Campaign',
			tokens: ['Campus Community Campaign', 'Campaign'],
		},
		{
			name: 'Canadian Union of Public Employees ( CUPE ) Local 4600',
			link: '//4600.cupe.ca/',
			category: 'Service',
			value: 'Canadian Union of Public Employees ( CUPE ) Local 4600',
			tokens: [
				'Canadian Union of Public Employees ( CUPE ) Local 4600',
				'CUPE 4600',
				'Union',
			],
		},
		{
			name: 'Career Services',
			link: '//carleton.ca/career/',
			category: 'Service',
			value: 'Career Services',
			tokens: ['Career Services', 'CO-OP', 'Careers', 'Co-op Office'],
		},
		{
			name: 'Carleton Central',
			link: '//central.carleton.ca',
			category: 'Service',
			value: 'Carleton Central',
			tokens: ['Carleton Central', 'Portal', 'Schedules', 'ERP'],
		},
		{
			name: 'Carleton Centre for Community Innovation (3ci)',
			link: '//carleton.ca/3ci/',
			category: 'Service',
			value: 'Carleton Centre for Community Innovation (3ci)',
			tokens: ['Carleton Centre for Community Innovation (3ci)'],
		},
		{
			name: 'Carleton CMS',
			link: '//carleton.ca/ccms/',
			category: 'Service',
			value: 'Carleton CMS',
			tokens: ['Carleton CMS', 'Content Management', 'Websites', 'WordPress'],
		},
		{
			name: 'Carleton International',
			link: '//carleton.ca/ci',
			category: 'Research',
			value: 'Carleton International',
			tokens: ['Carleton International', 'International'],
		},
		{
			name: 'Carleton Now - Community Magazine',
			link: '//now.carleton.ca/',
			category: 'Communications',
			value: 'Carleton Now - Community Magazine',
			tokens: ['Carleton Now - Community Magazine'],
		},
		{
			name: 'CETD',
			link: '//labs.carleton.ca/canadaeurope/',
			category: 'Lab',
			value: 'CETD',
			tokens: [
				'CETD',
				'Canada-Europe Transatlantic Dialogue',
				'Dialogue transatlantique',
			],
		},
		{
			name: 'Carleton Sound',
			link: '//carleton.ca/carletonsound/',
			category: 'Music',
			value: 'Carleton Sound',
			tokens: ['Carleton Sound'],
		},
		{
			name: 'Carleton University Academic Staff Association (CUASA)',
			link: '//caut.ca/cuasa/',
			category: 'Service',
			value: 'Carleton University Academic Staff Association (CUASA)',
			tokens: ['Carleton University Academic Staff Association (CUASA)', 'Union'],
		},
		{
			name: 'CUOL - Carleton University Online',
			link: '//carleton.ca/cuol/',
			category: 'Service',
			value: 'CUOL - Carleton University Online',
			tokens: ['CUOL', 'Carleton University Online', 'vod', 'Video On Demand'],
		},
		{
			name: 'Centre for Aboriginal Culture and Education (CACE)',
			link: '//carleton.ca/aboriginal',
			category: 'Students',
			value: 'Centre for Aboriginal Culture and Education (CACE)',
			tokens: ['Centre for Aboriginal Culture and Education (CACE)'],
		},
		{
			name: 'Centre for Applied Cognitive Research',
			link: '//carleton.ca/cacr/',
			category: 'Research',
			value: 'Centre for Applied Cognitive Research',
			tokens: ['Centre for Applied Cognitive Research'],
		},
		{
			name: 'Centre for Conflict Education and Research (CCER)',
			link: '//carleton.ca/ccer/',
			category: 'Department',
			value: 'Centre for Conflict Education and Research (CCER)',
			tokens: ['Centre for Conflict Education and Research (CCER)', 'CCER'],
		},
		{
			name: 'Centre for European Studies',
			link: '//carleton.ca/ces/',
			category: 'Service',
			value: 'Centre for European Studies',
			tokens: ['Centre for European Studies', 'CES'],
		},
		{
			name: 'Center for Governance and Public Management',
			link: '//carleton.ca/cgpm/',
			category: 'Service',
			value: 'Center for Governance and Public Management',
			tokens: ['Center for Governance and Public Management'],
		},
		{
			name: 'Centre for International Migration and Settlement Studies (CIMSS)',
			link: '//carleton.ca/cimss/',
			category: 'Service',
			value: 'Centre for International Migration and Settlement Studies (CIMSS)',
			tokens: [
				'Centre for International Migration and Settlement Studies (CIMSS)',
			],
		},
		{
			name: 'Centre for Initiatives in Education (CIE)',
			link: '//carleton.ca/cie/',
			category: 'Research',
			value: 'Centre for Initiatives in Education (CIE)',
			tokens: ['Centre for Initiatives in Education (CIE)'],
		},
		{
			name: 'Centre for Security and Defence Studies (CSDS)',
			link: '//carleton.ca/ctca',
			category: 'Research',
			value: 'Centre for Security and Defence Studies (CSDS)',
			tokens: ['Centre for Security and Defence Studies (CSDS)'],
		},
		{
			name: 'Centre for Transnational Cultural Analysis',
			link: '//carleton.ca/csds/',
			category: 'Research',
			value: 'Centre for Transnational Cultural Analysis',
			tokens: ['Centre for Transnational Cultural Analysis'],
		},
		{
			name: 'Centre on Values and Ethics (COVE)',
			link: '//carleton.ca/cove/',
			category: 'Research',
			value: 'Centre on Values and Ethics (COVE)',
			tokens: ['Centre on Values and Ethics (COVE)'],
		},
		{
			name: 'Centretown News',
			link: '//centretownnewsonline.ca/',
			category: 'Communications',
			value: 'Centretown News',
			tokens: ['Centretown News'],
		},
		{
			name: 'Chemistry, Department of',
			link: '//carleton.ca/chem/',
			category: 'Department',
			value: 'Chemistry, Department of',
			tokens: ['Chemistry, Department of'],
		},
		{
			name: 'Choir, Carleton University',
			link: '//carleton.ca/music/choir',
			category: 'Service',
			value: 'Choir, Carleton University',
			tokens: ['Choir, Carleton University'],
		},
		{
			name: 'Civil and Environmental Engineering, Department of',
			link: '//carleton.ca/cee',
			category: 'Department',
			value: 'Civil and Environmental Engineering, Department of',
			tokens: ['Civil and Environmental Engineering, Department of'],
		},
		{
			name: 'CKCU-FM 93.1',
			link: '//ckcufm.com/',
			category: 'Service',
			value: 'CKCU-FM 93.1',
			tokens: ['CKCU-FM 93.1', 'Radio'],
		},
		{
			name: 'Class Schedule',
			link: '//central.carleton.ca/prod/bwysched.p_select_term?wsea_code=EXT',
			category: 'Service',
			value: 'Class Schedule',
			tokens: ['Class Schedule'],
		},
		{
			name: 'Co-Curricular Record',
			link: '//carleton.ca/seo/ccr/',
			category: 'Students',
			value: 'Co-Curricular Record',
			tokens: ['Co-Curricular Record'],
		},
		{
			name: 'College of the Humanities',
			link: '//carleton.ca/chum/',
			category: 'Department',
			value: 'College of the Humanities',
			tokens: ['College of the Humanities'],
		},
		{
			name: 'Colonel by Child Care Centre',
			link: '//cbccc.ca/',
			category: 'Service',
			value: 'Colonel by Child Care Centre',
			tokens: ['Colonel by Child Care Centre', 'Day care'],
		},
		{
			name: 'Communications, Department of University',
			link: '//carleton.ca/duc/',
			category: 'Service',
			value: 'Communications, Department of University',
			tokens: ['Communications, Department of University'],
		},
		{
			name:
				'Comparative Studies in Literature, Art and Culture (ICSLAC), Institute for',
			link: '//carleton.ca/icslac/',
			category: 'Department',
			value:
				'Comparative Studies in Literature, Art and Culture (ICSLAC), Institute for',
			tokens: [
				'Comparative Studies in Literature, Art and Culture (ICSLAC), Institute for',
			],
		},
		{
			name: 'Computer Engineering, Department of Systems and',
			link: '//sce.carleton.ca/',
			category: 'Department',
			value: 'Computer Engineering, Department of Systems and',
			tokens: ['Computer Engineering, Department of Systems and'],
		},
		{
			name: 'CU Explore',
			link: '//carleton.ca/engineering-design/cuexplore/',
			category: 'Event',
			value: 'Engineering & Design, Faculty of',
			tokens: ['explore, gta, engineering, design, cuexplore, carleton explore'],
		},
		{
			name: 'Computer Science, School of',
			link: '//scs.carleton.ca/',
			category: 'Department',
			value: 'Computer Science, School of',
			tokens: ['Computer Science, School of'],
		},
		{
			name: 'Conference Services, Department of',
			link: '//conferenceservices.carleton.ca/',
			category: 'Conference',
			value: 'Conference Services, Department of',
			tokens: ['Conference Services, Department of', 'Conference'],
		},
		{
			name: 'Convocation Site',
			link: '//carleton.ca/convocation/',
			category: 'Students',
			value: 'Convocation Site',
			tokens: ['Convocation Site', 'graduation', 'Convocation'],
		},
		{
			name: 'Copyright Guidelines',
			link: '//library.carleton.ca/copyright/',
			category: 'Service',
			value: 'Copyright Guidelines',
			tokens: ['Copyright Guidelines'],
		},
		{
			name: 'Counselling Services, Health and',
			link: '//carleton.ca/health/',
			category: 'Service',
			value: 'Counselling Services, Health and',
			tokens: ['Counselling Services, Health and', 'Medical services'],
		},
		{
			name: 'Criminology and Criminal Justice',
			link: '//carleton.ca/criminology/',
			category: 'Department',
			value: 'Criminology and Criminal Justice',
			tokens: ['Criminology and Criminal Justice'],
		},
		{
			name: 'cuLearn - Learning Management System',
			link: 'https://carleton.ca/culearn/',
			category: 'LMS',
			value: 'cuLearn - Learning Management System',
			tokens: ['cuLearn - Learning Management System', 'LMS', 'online learning'],
		},
		{
			name: 'cuPortfolio',
			link: '//carleton.ca/cuportfoliosupport/',
			category: 'Students',
			value: 'cuPortfolio',
			tokens: ['cuPortfolio', 'ePortfolio'],
		},
		{
			name: 'CU Testing Centre',
			link: '//carleton.ca/testingcentre/',
			category: 'Academics',
			value: 'CU Testing Centre',
			tokens: [
				'exam',
				'examinations',
				'exams',
				'test',
				'testing',
				'proctor',
				'invigilation',
			],
		},
		{
			name: 'Dining Services',
			link: '//dining.carleton.ca',
			category: 'Service',
			value: 'Dining Services',
			tokens: [
				'Dining Services',
				'Food',
				'Restaurants',
				'Catering',
				'Coffee',
				'Food Services',
			],
		},
		{
			name: 'Directions to the Carleton Campus',
			link: '//carleton.ca/campus/directions/',
			category: 'Service',
			value: 'Directions to the Carleton Campus',
			tokens: ['Directions to the Carleton Campus'],
		},
		{
			name: 'Directory of Faculty and Staff',
			link: '//carleton.ca/phonebook/',
			category: 'Service',
			value: 'Directory of Faculty and Staff',
			tokens: [
				'Directory of Faculty and Staff',
				'phonebook',
				'emails',
				'White Pages',
			],
		},
		{
			name: 'Disabilities, Paul Menton Centre for Persons with',
			link: '//carleton.ca/pmc/',
			category: 'Students',
			value: 'Disabilities, Paul Menton Centre for Persons with',
			tokens: ['Disabilities, Paul Menton Centre for Persons with', 'AODA', 'PMC'],
		},
		{
			name: 'Earth Sciences, Department of',
			link: '//earthsci.carleton.ca',
			category: 'Department',
			value: 'Earth Sciences, Department of',
			tokens: ['Earth Sciences, Department of'],
		},
		{
			name: 'Economics, Department of',
			link: '//carleton.ca/economics/',
			category: 'Department',
			value: 'Economics, Department of',
			tokens: ['Economics, Department of'],
		},
		{
			name: 'Educational Development Centre (EDC)',
			link: '//carleton.ca/edc',
			category: 'Service',
			value: 'Educational Development Centre (EDC)',
			tokens: ['Educational Development Centre (EDC)', 'Faculty support'],
		},
		{
			name: 'Electronics, Department of',
			link: '//doe.carleton.ca',
			category: 'Department',
			value: 'Electronics, Department of',
			tokens: ['Electronics, Department of'],
		},
		{
			name: 'Emergency Management',
			link: '//carleton.ca/safety/emergencymanagement/',
			category: 'Service',
			value: 'Emergency Management',
			tokens: ['emergency', 'emergency management', 'management'],
		},
		{
			name: 'Engineering and Design, Faculty of',
			link: '//carleton.ca/engineering-design/',
			category: 'Faculty',
			value: 'Engineering and Design, Faculty of',
			tokens: ['Engineering and Design, Faculty of'],
		},
		{
			name: 'English Language and Literature, Department of',
			link: '//carleton.ca/english/',
			category: 'Department',
			value: 'English Language and Literature, Department of',
			tokens: ['English Language and Literature, Department of'],
		},
		{
			name: 'English as a Second Language (courses)',
			link: '//carleton.ca/slals/credit-esl/',
			category: 'Service',
			value: 'English as a Second Language (courses)',
			tokens: ['English as a Second Language (courses)'],
		},
		{
			name: 'Enriched Support Program',
			link: '//carleton.ca/esp/',
			category: 'Service',
			value: 'Enriched Support Program',
			tokens: ['Enriched Support Program'],
		},
		{
			name: 'Environmental Engineering, Department of Civil and',
			link: '//carleton.ca/cee',
			category: 'Department',
			value: 'Environmental Engineering, Department of Civil and',
			tokens: ['Environmental Engineering, Department of Civil and'],
		},
		{
			name: 'Environmental Health and Safety',
			link: '//carleton.ca/ehs/',
			category: 'Service',
			value: 'Environmental Health and Safety',
			tokens: ['Environmental Health and Safety'],
		},
		{
			name: 'Environmental Science, Insitute of',
			link: '//carleton.ca/envirosci/',
			category: 'Department',
			value: 'Environmental Science, Insitute of',
			tokens: ['Environmental Science, Insitute of'],
		},
		{
			name: 'Equity Services',
			link: '//carleton.ca/equity/',
			category: 'Service',
			value: 'Equity Services',
			tokens: ['Equity Services'],
		},
		{
			name: 'E-Reserves (Ares)',
			link:
				'https://www.library.carleton.ca/services/library-reserves-students/e-reserves-ares',
			category: 'Library',
			value: 'E-Reserves (Ares)',
			tokens: ['Ares', 'E-Reserves'],
		},
		{
			name: 'European, Russian and Eurasian Studies, Institute of',
			link: '//carleton.ca/eurus/',
			category: 'Service',
			value: 'European, Russian and Eurasian Studies, Institute of',
			tokens: ['European, Russian and Eurasian Studies, Institute of', 'EURUS'],
		},
		{
			name: 'EUCE Network',
			link: '//carleton.ca/euce-network-canada/',
			category: 'Department',
			value: 'EUCE Network',
			tokens: ['EUCE', 'EUCE Network'],
		},
		{
			name: 'Events Calendar, Carleton',
			link: '//events.carleton.ca',
			category: 'Service',
			value: 'Events Calendar, Carleton',
			tokens: ['Events Calendar, Carleton'],
		},
		{
			name: 'Exam Centre, McIntyre Information site',
			link: '//carleton.ca/exams/mcintyre-exam-centre/',
			category: 'Service',
			value: 'Exam Centre, McIntyre Information site',
			tokens: ['Exam Centre, McIntyre Information site', 'MEC'],
		},
		{
			name: 'Examinations Information site',
			link: '//carleton.ca/ses/',
			category: 'Students',
			value: 'Examinations Information site',
			tokens: ['Examinations Information site', 'Exams', 'Exam Timetables'],
		},
		{
			name: 'Experts &#8211; Carleton University Media Guide',
			link: '//newsroom.carleton.ca/experts/',
			category: 'Communications',
			value: 'Experts &#8211; Carleton University Media Guide',
			tokens: ['Experts &#8211; Carleton University Media Guide'],
		},
		{
			name: 'Facilities Management and Planning',
			link: '//carleton.ca/fmp',
			category: 'Service',
			value: 'Facilities Management and Planning',
			tokens: ['Facilities Management and Planning', 'FMP'],
		},
		{
			name: 'Faculty of Arts and Social Sciences',
			link: '//carleton.ca/fass/',
			category: 'Faculty',
			value: 'Faculty of Arts and Social Sciences',
			tokens: ['Faculty of Arts and Social Sciences', 'FASS'],
		},
		{
			name: 'Faculty of Graduate and Postdoctoral Affairs',
			link: '//carleton.ca/fgpa/',
			category: 'Graduate',
			value: 'Faculty of Graduate and Postdoctoral Affairs',
			tokens: [
				'Faculty of Graduate and Postdoctoral Affairs',
				'Graduate studies',
				'FGPA',
				'Master',
				'Master’s',
				'PhD',
				'Doctor',
				'Doctor of Philosophy',
				'Diplomas',
				'Post-grad',
				'Postgrad',
			],
		},
		{
			name: 'Faculty of Public Affairs',
			link: '//carleton.ca/fpa/',
			category: 'Faculty',
			value: 'Faculty of Public Affairs',
			tokens: ['Faculty of Public Affairs', 'FPA'],
		},
		{
			name: 'Faculty Recruitment and Support',
			link: '//carleton.ca/facultyrecruitment',
			category: 'Service',
			value: 'Faculty Recruitment and Support',
			tokens: ['Faculty Recruitment and Support'],
		},
		{
			name: 'Fees ( Tuition )',
			link: '//carleton.ca/studentaccounts',
			category: 'Service',
			value: 'Fees ( Tuition )',
			tokens: ['Fees ( Tuition )'],
		},
		{
			name: 'Film Studies (School for Studies in Art and Culture)',
			link: '//carleton.ca/filmstudies/',
			category: 'Department',
			value: 'Film Studies (School for Studies in Art and Culture)',
			tokens: ['Film Studies (School for Studies in Art and Culture)'],
		},
		{
			name: 'Finance and Administration',
			link: '//carleton.ca/finance-admin/',
			category: 'Service',
			value: '//carleton.ca/finance-admin/people/watt-duncan/',
			tokens: [
				'Financial Services',
				'Finance',
				'Admin',
				'Professional Services',
				'Fin',
				'F&A',
			],
		},
		{
			name: 'Financial Services',
			link: '//carleton.ca/finance/',
			category: 'Service',
			value: 'Financial Services',
			tokens: ['Financial Services', 'Finance'],
		},
		{
			name: 'Vice-President Finance and Administration',
			link: '//carleton.ca/finance-admin/people/watt-duncan/',
			category: 'Service',
			value: 'Financial Services',
			tokens: [
				'Financial Services',
				'Finance',
				'Admin',
				'Duncan Watt',
				'Professional Services',
				'vp',
			],
		},
		{
			name: 'French, Department of',
			link: '//carleton.ca/french/',
			category: 'Department',
			value: 'French, Department of',
			tokens: ['French, Department of'],
		},
		{
			name: 'French Linguistic Society',
			link: '//carleton.ca/fls/',
			category: 'Service',
			value: 'French Linguistic Society',
			tokens: ['French Linguistic Society'],
		},
		{
			name: 'Geography and Environmental Studies, Department of',
			link: '//carleton.ca/geography/',
			category: 'Department',
			value: 'Geography and Environmental Studies, Department of',
			tokens: ['Geography and Environmental Studies, Department of'],
		},
		{
			name: 'Go Ravens',
			link: '//goravens.ca',
			category: 'Service',
			value: 'Go Ravens',
			tokens: [
				'Go Ravens',
				'Varsity',
				'Football',
				'Basketball',
				'Soccer',
				'Ravens',
			],
		},
		{
			name: 'Graduate Students&#8217; Association (GSA)',
			link: '//gsacarleton.ca/',
			category: 'Students',
			value: 'Graduate Students&#8217; Association (GSA)',
			tokens: ['Graduate Students&#8217; Association (GSA)'],
		},
		{
			name: 'Current Graduate Students',
			link: 'https://gradstudents.carleton.ca',
			category: 'Graduate',
			value: 'Current Graduate Students',
			tokens: [
				'Current Graduate Students homepage',
				'Grad Students',
				'Grad',
				'Graduate',
				'Graduate Studies',
				'Master',
				'Master’s',
				'PhD',
				'Doctor',
				'Doctor of Philosophy',
				'Diplomas',
				'Post-grad',
				'Postgrad',
			],
		},
		{
			name: 'The Print Shop',
			link: '//carleton.ca/theprintshop/',
			category: 'Service',
			value: 'The Print Shop',
			tokens: ['Graphic Services', 'Print', 'Graphic'],
		},
		{
			name: 'Greek and Roman Studies (College of the Humanities)',
			link: '//carleton.ca/chum/greek-and-roman-studies/',
			category: 'Department',
			value: 'Greek and Roman Studies (College of the Humanities)',
			tokens: ['Greek and Roman Studies (College of the Humanities)'],
		},
		{
			name: 'Health Sciences, Department of',
			link: '//carleton.ca/healthsciences',
			category: 'Department',
			value: 'Health Sciences, Department of',
			tokens: ['Health Sciences, Department of'],
		},
		{
			name: 'Healthy Workplace',
			link: '//carleton.ca/healthy-workplace/',
			category: 'Service',
			value: 'Healthy Workplace',
			tokens: ['Healthy Workplace', 'Staff and Faculty wellness'],
		},
		{
			name: 'History, Department of',
			link: '//carleton.ca/history/',
			category: 'Department',
			value: 'History, Department of',
			tokens: ['History, Department of'],
		},
		{
			name: 'Housing and Residence Life Services, Department of',
			link: '//housing.carleton.ca/',
			category: 'Students',
			value: 'Housing and Residence Life Services, Department of',
			tokens: ['Housing and Residence Life Services, Department of', 'Residence'],
		},
		{
			name: 'Human Resources, Department of',
			link: '//carleton.ca/hr',
			category: 'Service',
			value: 'Human Resources, Department of',
			tokens: ['Human Resources, Department of', 'HR', 'jobs', 'working'],
		},
		{
			name: 'Indigenous and Canadian Studies, School of',
			link: '//carleton.ca/canadianstudies/',
			category: 'Department',
			value: 'Canadian Studies, School of',
			tokens: [
				'Indigenous and Canadian Studies, School of',
				'Department',
				'Canadian Studies',
				'Indigenous',
			],
		},
		{
			name: 'Industrial Design, School of',
			link: '//id.carleton.ca/',
			category: 'Department',
			value: 'Industrial Design, School of',
			tokens: ['Industrial Design, School of', 'ID'],
		},
		{
			name: 'Information Carleton',
			link: '//carleton.ca/infocarleton/',
			category: 'Service',
			value: 'Information Carleton',
			tokens: ['Information Carleton'],
		},
		{
			name: 'Information Technology Services ( ITS )',
			link: '//carleton.ca/its',
			category: 'Service',
			value: 'Information Technology Services ( ITS )',
			tokens: [
				'Information Technology Services ( ITS )',
				'IT',
				'Information Technology',
				'CCS',
				'Computing Communications Services',
				'Help Desk',
			],
		},
		{
			name: 'Infrastructure Protection and International Security, Master of',
			link: '//carleton.ca/ipis/',
			category: 'Graduate',
			value: 'Infrastructure Protection and International Security, Master of',
			tokens: ['Infrastructure Protection and International Security, Master of'],
		},
		{
			name: 'Initiatives in Education (CIE), Centre for',
			link: '//carleton.ca/cie/',
			category: 'Research',
			value: 'Initiatives in Education (CIE), Centre for',
			tokens: ['Initiatives in Education (CIE), Centre for'],
		},
		{
			name: 'Institute of Cognitive Science',
			link: '//carleton.ca/ics/',
			category: 'Research',
			value: 'Institute of Cognitive Science',
			tokens: ['Institute of Cognitive Science'],
		},
		{
			name: 'Institute of Health: Science Technology and Policy',
			link: '//institute-health.carleton.ca/',
			category: 'Research',
			value: 'Institute of Health: Science Technology and Policy',
			tokens: ['Institute of Health: Science Technology and Policy'],
		},
		{
			name: 'Institutional Research and Planning, Office of',
			link: '//oirp.carleton.ca/',
			category: 'Service',
			value: 'Institutional Research and Planning, Office of',
			tokens: ['Institutional Research and Planning, Office of', 'Statistics'],
		},
		{
			name: 'Instructional Media Services (IMS)',
			link: '//carleton.ca/ims/',
			category: 'Service',
			value: 'Instructional Media Services (IMS)',
			tokens: ['Instructional Media Services (IMS)'],
		},
		{
			name: 'iTeam',
			link: '//carleton.ca/iteam/',
			category: 'Service',
			value: 'iTeam',
			tokens: [
				'iTeam',
				'Apple support',
				'iPad',
				'iPhone',
				'iOS',
				'Macintosh',
				'OSX',
				'tablet',
				'Mel',
				'Ben',
				'Char',
			],
		},
		{
			name: 'Interdisciplinary Science and Practice',
			link: '//carleton.ca/isap/',
			category: 'Service',
			value: 'Interdisciplinary Science and Practice',
			tokens: ['Interdisciplinary Science and Practice'],
		},
		{
			name: 'Interdisciplinary Studies, Institute of (IIS)',
			link: '//carleton.ca/iis/',
			category: 'Service',
			value: 'Interdisciplinary Studies, Institute of (IIS)',
			tokens: [
				'Interdisciplinary Studies, Institute of (IIS)',
				'IIS',
				'Child Studies',
				'Disability Studies',
				'Directed Interdisciplinary Studies',
				'Human Rights',
				'Latin American and Caribbean Studies',
				'South Asian Studies',
				'Sexuality Studies',
			],
		},
		{
			name: 'International Affairs (NPSIA), Norman Paterson School of',
			link: '//carleton.ca/npsia/',
			category: 'Research',
			value: 'International Affairs (NPSIA), Norman Paterson School of',
			tokens: ['International Affairs (NPSIA), Norman Paterson School of'],
		},
		{
			name: 'International Student Services Office',
			link: '//carleton.ca/isso/',
			category: 'Service',
			value: 'International Student Services Office',
			tokens: ['International Student Services Office', 'ISSO'],
		},
		{
			name: 'International Students Information',
			link: '//admissions.carleton.ca/applicant-type/international-applicants/',
			category: 'Admissions',
			value: 'International Students Information',
			tokens: ['International Students Information'],
		},
		{
			name: 'IT Service Catalogue',
			link: '//carleton.ca/itservicecatalogue',
			category: 'Services',
			value: 'IT Service Catalogue',
			tokens: ['IT Service Catalogue', 'IT Service Catalog', 'Services'],
		},
		{
			name: 'Jewish Studies, Max and Tessie Zelikovitz Centre for',
			link: '//carleton.ca/jewishstudies/',
			category: 'Department',
			value: 'Jewish Studies, Max and Tessie Zelikovitz Centre for',
			tokens: ['Jewish Studies, Max and Tessie Zelikovitz Centre for'],
		},
		{
			name: 'Journalism and Communication, School of',
			link: '//carleton.ca/sjc/',
			category: 'Department',
			value: 'Journalism and Communication, School of',
			tokens: ['Journalism and Communication, School of', 'Mass Communications'],
		},
		{
			name: 'Kailash Mital Theatre &#8211; monthly schedule of events',
			link: '//carleton.ca/km-theatre',
			category: 'Theatre',
			value: 'Kailash Mital Theatre &#8211; monthly schedule of events',
			tokens: ['Kailash Mital Theatre &#8211; monthly schedule of events'],
		},
		{
			name: 'Law, Department of',
			link: '//carleton.ca/law/',
			category: 'Department',
			value: 'Law, Department of',
			tokens: ['Law, Department of'],
		},
		{
			name: 'Learning in Retirement',
			link: '//carleton.ca/linr/',
			category: 'Service',
			value: 'Learning in Retirement',
			tokens: ['Learning in Retirement'],
		},
		{
			name: 'Library, Maxwell MacOdrum',
			link: '//library.carleton.ca/',
			category: 'Academics',
			value: 'Library, Maxwell MacOdrum',
			tokens: ['Library, Maxwell MacOdrum', 'Carleton Library', 'Library'],
		},
		{
			name: 'Mail Services',
			link: '//carleton.ca/mailservices/',
			category: 'Service',
			value: 'Mail Services',
			tokens: ['Mail Services'],
		},
		{
			name: 'Management Development Program for Women',
			link:
				'//sprott.carleton.ca/our-programs/management-development-program-for-women/',
			category: 'Program',
			value: 'Management Development Program for Women',
			tokens: ['Management Development Program for Women'],
		},
		{
			name: 'Map of Campus',
			link: '//carleton.ca/campus/map',
			category: 'Service',
			value: 'Map of Campus',
			tokens: ['Map of Campus', 'Map'],
		},
		{
			name: 'Mathematics and Statistics, School of',
			link: '//carleton.ca/math',
			category: 'Department',
			value: 'Mathematics and Statistics, School of',
			tokens: ['Mathematics and Statistics, School of'],
		},
		{
			name: 'Mechanical and Aerospace Engineering, Department of',
			link: '//mae.carleton.ca/',
			category: 'Department',
			value: 'Mechanical and Aerospace Engineering, Department of',
			tokens: ['Mechanical and Aerospace Engineering, Department of'],
		},
		{
			name: 'Media Production Centre (MPC)',
			link: '//carleton.ca/mpc/',
			category: 'Service',
			value: 'Media Production Centre (MPC)',
			tokens: [
				'Media Production Centre (MPC)',
				'Video Production',
				'MPC',
				'Live Video Streaming',
				'Videoconferencing',
				'Video editing',
			],
		},
		{
			name: 'Mental Health and Well-Being',
			link: 'https://carleton.ca/wellness/living-well/',
			category: 'Service',
			value: 'Mental Health and Well-Being',
			tokens: [
				'wellness',
				'mental health',
				'well being',
				'mental health resources',
				'wellness support',
			],
		},
		{
			name: 'Mobile Services',
			link: 'https://carleton.ca/mobileservices/',
			category: 'Service',
			value: 'Mental Health and Well-Being',
			tokens: [
				'cell phone plans',
				'mobile phone plans',
				'rogers phone plan',
				'employee cell phones',
				'Corporate cell phone account',
				'Mobile devices',
				'Cell phones',
				'Mobile services',
				'Travel packages',
				'iPhone',
				'Blackberry',
				'Android',
			],
		},
		{
			name: 'Music (School for Studies in Art and Culture)',
			link: '//carleton.ca/music/',
			category: 'Department',
			value: 'Music (School for Studies in Art and Culture)',
			tokens: ['Music (School for Studies in Art and Culture)'],
		},
		{
			name: 'MyCarleton - Current Student Homepage',
			link: 'https://students.carleton.ca',
			category: 'Students',
			value: 'MyCarleton - Current Student Homepage',
			tokens: [
				'MyCarleton - Current Student Homepage',
				'Portal',
				'Student login',
				'Students',
				'Student News',
			],
		},
		{
			name: 'Neuroscience',
			link: '//carleton.ca/neuroscience/',
			category: 'Department',
			value: 'Neuroscience',
			tokens: ['Neuroscience'],
		},
		{
			name: 'Newsroom',
			link: '//newsroom.carleton.ca',
			category: 'Service',
			value: 'Newsroom',
			tokens: ['Newsroom', 'News Releases', 'Media Advisories', 'PSAs'],
		},
		{
			name: 'Ombuds Services (includes the CU Survival Guide)',
			link: '//carleton.ca/ombuds/',
			category: 'Service',
			value: 'Ombuds Services (includes the CU Survival Guide)',
			tokens: ['Ombuds Services (includes the CU Survival Guide)'],
		},
		{
			name: 'Organizational Chart',
			link: '//carleton.ca/about/university-executive/',
			category: 'Service',
			value: 'Organizational Chart',
			tokens: ['Organizational Chart', 'Org Chart'],
		},
		{
			name: 'Orientation @ Carleton',
			link: '//carleton.ca/orientation/',
			category: 'Students',
			value: 'Orientation @ Carleton',
			tokens: ['Orientation @ Carleton', 'New students', 'Frosh'],
		},
		{
			name: 'Parking and Lockers',
			link: '//carleton.ca/parking/',
			category: 'Service',
			value: 'Parking and Lockers',
			tokens: ['Parking and Lockers', 'lockers'],
		},
		{
			name: 'Patrol Services',
			link: '//carleton.ca/patrol/',
			category: 'Service',
			value: 'Patrol Services',
			tokens: ['Patrol Services'],
		},
		{
			name: 'Pauline Jewett Institute of Women&#8217;s and Gender Studies',
			link: '//carleton.ca/womensstudies/',
			category: 'Department',
			value: 'Pauline Jewett Institute of Women&#8217;s and Gender Studies',
			tokens: [
				'Pauline Jewett Institute of Women&#8217;s and Gender Studies',
				'Women&#8217;s Studies',
			],
		},
		{
			name: 'Pension Fund Management',
			link: '//carleton.ca/finance-admin/pension-fund-management/',
			category: 'Service',
			value: 'Pension Fund Management',
			tokens: ['Pension Fund Management'],
		},
		{
			name: 'Peer-Assisted Study Sessions (PASS)',
			link: '//carleton.ca/sasc/peer-assisted-study-sessions/',
			category: 'Students',
			value: 'Peer-Assisted Study Sessions (PASS)',
			tokens: ['Peer-Assisted Study Sessions (PASS)', 'PASS'],
		},
		{
			name: 'Philosophy, Department of',
			link: '//carleton.ca/philosophy/',
			category: 'Department',
			value: 'Philosophy, Department of',
			tokens: ['Philosophy, Department of'],
		},
		{
			name: 'Physics, Department of',
			link: '//physics.carleton.ca/',
			category: 'Department',
			value: 'Physics, Department of',
			tokens: ['Physics, Department of'],
		},
		{
			name: 'Political Economy, Institute of',
			link: '//carleton.ca/polecon/',
			category: 'Department',
			value: 'Political Economy, Institute of',
			tokens: ['Political Economy, Institute of'],
		},
		{
			name: 'Political Management, Clayton H. Riddell Graduate Program in',
			link: '//carleton.ca/politicalmanagement/',
			category: 'Service',
			value: 'Political Management, Clayton H. Riddell Graduate Program in',
			tokens: ['Political Management, Clayton H. Riddell Graduate Program in'],
		},
		{
			name: 'Political Science, Department of',
			link: '//carleton.ca/polisci/',
			category: 'Department',
			value: 'Political Science, Department of',
			tokens: ['Political Science, Department of'],
		},
		{
			name: 'President, Office of the',
			link: '//carleton.ca/president/',
			category: 'Administration',
			value: 'President, Office of the',
			tokens: ['President, Office of the', 'President'],
		},
		{
			name: 'Privacy Office',
			link: '//carleton.ca/privacy/',
			category: 'Administration',
			value: 'Privacy Office',
			tokens: ['Privacy Office'],
		},
		{
			name: 'Professional Programs (Sprott School of Business)',
			link: '//sprott.carleton.ca/our-programs/professional-programs/',
			category: 'Academics',
			value: 'Professional Programs (Sprott School of Business)',
			tokens: [
				'Professional Development Programs (School of Business)',
				'Professional development',
				'Professional programs',
				'Executive education',
				'Continuing education',
				'Continuing ed',
				'Project management',
				'Business analysis',
				'Public management',
				'Leadership',
				'Management training',
				'Training',
				'Human resources program',
				'Human resources courses',
				'Public management',
				'Business process management',
				'Management skills',
				'Public sector and nonprofit marketing',
				'Risk management',
				'Social media program',
				'Internal auditor',
				'Leadership training',
				'Conflict resolution',
				'Pmp',
				'Pmp prep course',
				'Writing skills',
			],
		},
		{
			name: 'Project Office ( PMO )',
			link: '//carleton.ca/ccs/pmo',
			category: 'Service',
			value: 'Project Office ( PMO )',
			tokens: ['Project Office ( PMO )'],
		},
		{
			name: 'Provost and Vice-President (Academic)',
			link: '//carleton.ca/provost/',
			category: 'Administration',
			value: 'Provost and Vice-President (Academic)',
			tokens: ['Provost and Vice-President (Academic)'],
		},
		{
			name: 'Psychology, Department of',
			link: '//carleton.ca/psychology/',
			category: 'Department',
			value: 'Psychology, Department of',
			tokens: ['Psychology, Department of'],
		},
		{
			name: 'Public Policy and Administration, School of ( SPPA )',
			link: '//carleton.ca/sppa/',
			category: 'Department',
			value: 'Public Policy and Administration, School of ( SPPA )',
			tokens: ['Public Policy and Administration, School of ( SPPA )'],
		},
		{
			name: 'Purchasing Services',
			link: '//carleton.ca/purchasing/',
			category: 'Service',
			value: 'Purchasing Services',
			tokens: ['Purchasing Services'],
		},
		{
			name: 'Quality Assurance (Academic Programs), Office of',
			link: '//carleton.ca/viceprovost/cyclical-program-review/',
			category: 'Academic',
			value: 'Quality Assurance (Academic Programs), Office of',
			tokens: ['Quality Assurance (Academic Programs), Office of'],
		},
		{
			name: 'Quality Initiatives, Office of',
			link: '//carleton.ca/qualityinitiatives',
			category: 'Administration',
			value: 'Quality Initiatives, Office of',
			tokens: ['Quality Initiatives, Office of'],
		},
		{
			name: 'Records Management',
			link: '//carleton.ca/records/',
			category: 'Service',
			value: 'Records Management',
			tokens: ['Records Management'],
		},
		{
			name: 'Registrar&#8217;s Office',
			link: '//carleton.ca/registrar',
			category: 'Students',
			value: 'Registrar&#8217;s Office',
			tokens: ['Registrar&#8217;s Office', 'Transcripts'],
		},
		{
			name: 'Registration',
			link: '//carleton.ca/registrar/registration/',
			category: 'Students',
			value: 'Registration',
			tokens: ['Registration'],
		},
		{
			name: 'Religion (College of the Humanities)',
			link: '//carleton.ca/chum/religion/',
			category: 'Department',
			value: 'Religion (College of the Humanities)',
			tokens: ['Religion (College of the Humanities)'],
		},
		{
			name: 'Research at Carleton',
			link: '//carleton.ca/research',
			category: 'Research',
			value: 'Research at Carleton',
			tokens: ['Research at Carleton', 'Research'],
		},
		{
			name: 'Research Office, Carleton University',
			link: '//carleton.ca/curo',
			category: 'Research',
			value: 'Research Office, Carleton University',
			tokens: ['Research Office, Carleton University'],
		},
		{
			name: 'Research Works',
			link: '//researchworks.carleton.ca/',
			category: 'Research',
			value: 'Research Works',
			tokens: ['Research Works'],
		},
		{
			name: 'Safety',
			link: '//carleton.ca/safety/',
			category: 'Service',
			value: 'Safety',
			tokens: ['Safety'],
		},
		{
			name: 'School for Studies in Art and Culture',
			link: '//carleton.ca/ssac/',
			category: 'Department',
			value: 'School for Studies in Art and Culture',
			tokens: ['School for Studies in Art and Culture'],
		},
		{
			name: 'Science Student Success Centre',
			link: 'https://sssc.carleton.ca',
			category: 'Students',
			value: 'Science Student Success Centre',
			tokens: ['Science Student Success Centre'],
		},
		{
			name: 'Science Technology Centre',
			link: '//carleton.ca/stc/',
			category: 'Research',
			value: 'Science Technology Centre',
			tokens: ['Science Technology Centre'],
		},
		{
			name: 'Secretariat, University',
			link: '//carleton.ca/secretariat/',
			category: 'Administration',
			value: 'Secretariat, University',
			tokens: ['Secretariat, University'],
		},
		{
			name: 'Senate',
			link: '//carleton.ca/senate/',
			category: 'Administration',
			value: 'Senate',
			tokens: ['Senate'],
		},
		{
			name: 'Sexual Assault',
			link:
				'  //carleton.ca/equity/human-rights/policy/sexual-harassment-prevention-policy/',
			category: 'Students',
			value: 'Sexual Assault Support Services',
			tokens: ['Sexual Assault', 'Sexual Harrasment'],
		},
		{
			name: 'Sexual Assault Support Services',
			link: '//carleton.ca/equity/sexual-assault-support-services/',
			category: 'Service',
			value: 'Sexual Assault Support Services',
			tokens: ['Sexual Assault Support Services'],
		},
		{
			name: 'Sexual Harassment Prevention Policy',
			link:
				'//carleton.ca/equity/human-rights/policy/sexual-harassment-prevention-policy/',
			category: 'Service',
			value: 'Sexual Harassment Prevention Policy',
			tokens: ['Sexual Harassment Prevention Policy'],
		},
		{
			name: 'Social Work, School of',
			link: '//carleton.ca/ssw/',
			category: 'Department',
			value: 'Social Work, School of',
			tokens: ['Social Work, School of'],
		},
		{
			name: 'Sociology and Anthropology, Department of',
			link: '//carleton.ca/socanth/',
			category: 'Department',
			value: 'Sociology and Anthropology, Department of',
			tokens: ['Sociology and Anthropology, Department of'],
		},
		{
			name: 'Sock &#8216;n&#8217; Buskin Theatre Company',
			link: '//carleton.ca/socknbuskin/',
			category: 'Theatre',
			value: 'Sock &#8216;n&#8217; Buskin Theatre Company',
			tokens: ['Sock &#8216;n&#8217; Buskin Theatre Company'],
		},
		{
			name: 'Staff and Faculty homepage',
			link: 'https://carleton.ca/me',
			category: 'Staff-Faculty',
			value: 'Staff and Faculty homepage',
			tokens: [
				'Staff and Faculty homepage',
				'Employee homepage',
				'Staff Faculty login',
			],
		},
		{
			name: 'Statistics, School of Mathematics and',
			link: '//carleton.ca/math',
			category: 'Department',
			value: 'Statistics, School of Mathematics and',
			tokens: ['Statistics, School of Mathematics and'],
		},
		{
			name: 'Student Academic Success Centre',
			link: '//carleton.ca/sasc/',
			category: 'Students',
			value: 'Student Academic Success Centre',
			tokens: ['Student Academic Success Centre'],
		},
		{
			name: 'Students Accounts',
			link: '//carleton.ca/studentaccounts/',
			category: 'Administration',
			value: 'Students Accounts',
			tokens: ['Students Accounts'],
		},
		{
			name: 'Students Affairs',
			link: '//carleton.ca/studentaffairs/',
			category: 'Students',
			value: 'Students Affairs',
			tokens: ['Students Affairs'],
		},
		{
			name: 'Student Experience Office (SEO)',
			link: '//carleton.ca/seo/',
			category: 'Service',
			value: 'Student Experience Office (SEO)',
			tokens: ['Student Experience Office (SEO)'],
		},
		{
			name: 'Student Support',
			link: '//carleton.ca/studentsupport/',
			category: 'Students',
			value: 'Student Support',
			tokens: ['Student Support'],
		},
		{
			name: 'Summer Session (Calendar Supplement)',
			link: '//carleton.ca/summer/',
			category: 'Students',
			value: 'Summer Session (Calendar Supplement)',
			tokens: ['Summer Session (Calendar Supplement)'],
		},
		{
			name: 'Systems and Computer Engineering, Department of',
			link: '//sce.carleton.ca/',
			category: 'Department',
			value: 'Systems and Computer Engineering, Department of',
			tokens: ['Systems and Computer Engineering, Department of'],
		},
		{
			name: 'Office of the Associate Vice-President (Teaching and Learning)',
			link: '//carleton.ca/provost/',
			category: 'Academics',
			value: 'Office of the Associate Vice-President (Teaching and Learning)',
			tokens: ['Office of the Associate Vice-President (Teaching and Learning)'],
		},
		{
			name: 'Teaching and Learning Services',
			link: '//carleton.ca/teachinglearning/',
			category: 'Service',
			value: 'Teaching and Learning Services',
			tokens: [
				'Teaching and Learning Services',
				'Office of the Associate Vice-President',
			],
		},
		{
			name: 'Tuition Fees',
			link: '//carleton.ca/studentaccounts/',
			category: 'Service',
			value: 'Tuition Fees',
			tokens: ['Tuition Fees'],
		},
		{
			name: 'United Way Campaign',
			link: '//carleton.ca/unitedway',
			category: 'Charity',
			value: 'United Way Campaign',
			tokens: ['United Way Campaign'],
		},
		{
			name: 'University Policies',
			link: '//carleton.ca/secretariat/policies',
			category: 'Administration',
			value: 'University Policies',
			tokens: ['University Policies'],
		},
		{
			name: 'University Services (Administrative)',
			link: '//carleton.ca/univservices/',
			category: 'Service',
			value: 'University Services (Administrative)',
			tokens: ['University Services (Administrative)'],
		},
		{
			name: 'Vice-President (Academic), Provost and',
			link: '//carleton.ca/provost/',
			category: 'Service',
			value: 'Vice-President (Academic), Provost and',
			tokens: ['Vice-President (Academic), Provost and'],
		},
		{
			name: 'Vice-President (Finance and Administration)',
			link: '//carleton.ca/fin-admin/',
			category: 'Service',
			value: 'Vice-President (Finance and Administration)',
			tokens: ['Vice-President (Finance and Administration)'],
		},
		{
			name: 'Vice-President (Research and International)',
			link:
				'//carleton.ca/about/university-executive/the-vice-president-research-and-international/',
			category: 'Service',
			value: 'Vice-President (Research and International)',
			tokens: ['Vice-President (Research and International)'],
		},
		{
			name: 'Vice-Provost',
			link: '//carleton.ca/viceprovost/',
			category: 'Office',
			value: 'Vice-Provost',
			tokens: ['Vice-Provost'],
		},
		{
			name: 'Virtual Ventures',
			link: '//vv.carleton.ca/',
			category: 'Service',
			value: 'Virtual Ventures',
			tokens: ['Virtual Ventures'],
		},
		{
			name: 'Web Services',
			link: '//carleton.ca/webservices',
			category: 'Service',
			value: 'Web Services',
			tokens: ['Web Services', 'websites'],
		},
		{
			name: 'Writing Tutorial Service',
			link: '//carleton.ca/sasc/writing-tutorial-service/',
			category: 'Service',
			value: 'Writing Tutorial Service',
			tokens: ['Writing Tutorial Service'],
		},
		{
			name: 'El Taco',
			link: '//dannybrown.ca/dabomb',
			category: 'Awesomeland',
			value: 'El Taco',
			tokens: ['Cowboy Hat'],
		},
	];

	const searchForm = document.getElementById('searchform');
	const button = searchForm.querySelector('button');
	const searchInput = document.getElementById('cu-search__input');
	const target = document.getElementById('cu-search__results');

	searchInput.addEventListener('input', e => {
		let userInput = e.target.value;
		let results = [];

		//filter results and template
		for (item of data) {
			item.tokens.map(token => {
				if (token.toLowerCase().includes(userInput.toLowerCase())) {
					let res = `
					<a href="${item.link}">
						<li data-cat="${item.category}">${item.name}</li>
					</a>`;

					results.push(res);
				}
			});
		}

		// clear target on focusout
		searchInput.addEventListener('focusout', () => {
			target.innerHTML = '';
		});

		// show no results for empty strings or array
		// prevent form submition on empty search or enter key
		if (
			userInput === ' ' ||
			userInput === '' ||
			!Array.isArray(results) ||
			!results.length
		) {
			button.disabled = true;
			target.innerHTML = '<p>No Results..</p>';
		} else {
			button.disabled = false;
			target.innerHTML = results.join(' ');
		}
	});
});
